name: mtg-class
channels:
  - defaults
dependencies:
  - pip=19.2.3
  - python=3.7.4
  - spacy=2.0.16
  - pip:
      - nltk==3.4.5
      - gensim==3.8.1
      - pandas==0.24.1
      - numpy==1.16.1
      - jupyter==1.0.0
      - fasttext==0.9.1
      - sklearn==0.0
